[package]
name = "tiermaster_api_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["serde_json", "json"] }
serde = "1.0.217"
redis = "*"
serde_json = "1.0.134"